const { fetchTldr } = require('../lib/tldr');
const { sendTimedJson } = require('../lib/db');
const { allowMethods, sendError, setDataCacheHeaders } = require('../lib/http');
const { RATE_LIMITS, checkRateLimit } = require('../lib/rateLimit');

module.exports = async function handler(req, res) {
  if (!allowMethods(req, res)) {
    return;
  }

  if (!checkRateLimit(req, res, RATE_LIMITS.articles)) {
    return;
  }

  try {
    // Digests are generated by hand for now (scripts/tldr_all.py, no scheduler
    // yet), so a short edge cache is about freshness of the read, not of the
    // underlying data -- matches topics.js/trending.js's cadence.
    setDataCacheHeaders(res);
    await sendTimedJson(res, () => fetchTldr({ topic: req.query.topic }));
  } catch (err) {
    sendError(res, 'Failed to fetch TLDR digest', err, req);
  }
};
